# -*- coding: utf-8 -*-
"""Rail-ArcGIS API Call.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gZrvik9TjnBtCmbrJouXzerC4yb-0N8q
"""

import pandas as pd
from sqlalchemy import create_engine
import requests

def extract(url):
    df = requests.get(url)
    return df

url = "https://services.arcgis.com/Aur8tCo478N3VovT/arcgis/rest/services/NJ_Passenger_Rail_Stations/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson"
response = extract(url)
print(response.status_code)

data = response.json()
print(data.keys())

features = data['features']

print(len(features))

df = pd.json_normalize(features)

print(df.head(10))

def extract(url):
  response = requests.get(url)
  data = response.json()
  features = data['features']
  df = pd.json_normalize(features)
  return(df)

df = extract(url)
print(df.head(5))

def transform(df):

        df.groupby('properties.COUNTY').size()

        stationsper_county = df.groupby('properties.COUNTY').size()

        return stationsper_county

result = transform(df)
print(result)

def load(df):
  engine = create_engine('sqlite:///stations.db')
  df.to_sql('rail_stations', engine, if_exists='replace')

load(result)

print(result)

import sqlite3
conn = sqlite3.connect('stations.db')
print(pd.read_sql('SELECT * FROM rail_stations', conn))

def main():
    df = extract(url)
    result = transform(df)
    load(result)



